site_name: Vaishnav Raja – Engineering Portfolio
site_url: https://VaishnavRaja11.github.io/portfolio
repo_url: https://github.com/VaishnavRaja11/portfolio
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - search.suggest
    - content.code.copy
plugins:
  - search
  - tags
nav:
  - Overview: index.md
  - Resume: resume.md
  - Hardware Projects: hardware-projects.md
  - Software Projects: software-projects.md
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
