<<<<<<< HEAD
site_name: Vaishnav Raja
site_description: Portfolio of Vaishnav Raja's engineering projects and resume.
site_author: Vaishnav Raja
site_url: https://VaishnavRaja11.github.io/portfolio
=======
site_name: Vaishnav Raja – Engineering Portfolio
site_url: https://VaishnavRaja.github.io/portfolio
>>>>>>> f77350093e14a0976fa15589fc9090debf432815
repo_url: https://github.com/VaishnavRaja11/portfolio
theme:
  name: material
  features:
    - toc.integrate
    - navigation.tabs
    # - navigation.top
    - navigation.instant
    # - navigation.sections
    - navigation.tabs
    - search.suggest
    - content.code.copy
plugins:
  - search
  - tags
  # - glightbox
nav:
  - Overview: index.md
  - Resume: resume.md
  - Projects: projects.md
  # - Contacts: contact.md
extra_css:
  - stylesheets/portfolio.css
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - footnotes
  - pymdownx.emoji: 
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/VaishnavRaja11
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vaishnavraja
      name: LinkedIn
    - icon: fontawesome/solid/envelope
      link: mailto:vaishnavraja11@gmail.com
      name: Email
    # - icon: fontawesome/brands/google
    #   link: https://mail.google.com/mail/?view=cm&to=youremail@gmail.com
    #   name: Gmail
    # - icon: fontawesome/brands/email
    #   link: vaishnavraja11@gmail.com
    #   name: Email
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/YOUR-HANDLE
    #   name: Twitter
    # - icon: fontawesome/solid/envelope
    #   link: mailto:youremail@example.com
    #   name: Email

